"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$clean\
$custom\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "dimmed"

[character]
success_symbol = "[❯](black)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](black)"

[custom.clean]
command = "git symbolic-ref --short HEAD"
when = "! git-change"
style = "fg:black"
shell = "zsh"

[custom.dirty]
command = "git symbolic-ref --short HEAD"
when = "git-change"
style = "italic fg:black"
shell = "zsh"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
